{% set name = "flask-restplus" %}
{% set version = "0.11.0" %}
{% set sha256 = "1664401e61bcec4fdcfbfd25df81b233fe7388a6ae73c37b78918957609508b6" %}
{% set module_name = name.replace('-', '_') %}
{% set wheel_name = module_name + '-' + version + '-py2.py3-none-any.whl' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/26/cf/8c12fe4ccd1dadb6fa5e7f95065c894740f3a053454daeb8af6ff266de0f/{{ wheel_name }}
  sha256: {{ sha256 }}

build:
  number: 1
  script: python -m pip install --no-deps --ignore-installed {{ wheel_name }}

requirements:
  build:
    - python
    - pip
  run:
    - python
    - flask >=0.8
    - six >=1.3.0
    - jsonschema
    - pytz
    - aniso8601 >=0.82
    - enum34  # [py2k]
 
test:
  imports:
    - flask_restplus
  commands:
    - test -f "${SP_DIR}/{{ name.replace('-', '_') }}/static/swagger-ui.js"      # [unix]
    - test -f "${SP_DIR}/{{ name.replace('-', '_') }}/static/swagger-ui.css"      # [unix]
    - if not exist %SP_DIR%\\{{ name.replace('-', '_') }}\\static\\swagger-ui.js exit 1  # [win]
    - if not exist %SP_DIR%\\{{ name.replace('-', '_') }}\\static\\swagger-ui.css exit 1  # [win]

about:
  home: https://github.com/noirbizarre/flask-restplus
  license: MIT
  license_family: MIT
  license_file: {{ RECIPE_DIR }}/LICENSE
  summary: 'Fully featured framework for fast, easy and documented API development with Flask'

  description: |
    Flask-RESTPlus is an extension for Flask that adds support for quickly
    building REST APIs. Flask-RESTPlus encourages best practices with minimal
    setup. If you are familiar with Flask, Flask-RESTPlus should be easy to
    pick up. It provides a coherent collection of decorators and tools to
    describe your API and expose its documentation properly using Swagger.
  doc_url: http://flask-restplus.readthedocs.org/
  dev_url: https://github.com/noirbizarre/flask-restplus

extra:
  recipe-maintainers:
    - frol