{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: flask-restplus
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "0.1_4"

source:
  url: https://github.com/noirbizarre/flask-restplus/archive/0.11.0.tar.gz
  md5: 29fbffd9a103b472d953f8100d1116b5

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python =3.6
    - setuptools
    - flask >=0.8
    - six >=1.3.0
    - jsonschema
    - pytz
    - aniso8601 >=0.82
    - enum34  # [py2k]

  run:
    - python =3.6
    - flask >=0.8
    - six >=1.3.0
    - jsonschema
    - pytz
    - aniso8601 >=0.82
    - enum34  # [py2k]

test:
  imports:
    - flask_restplus

about:
  home: https://github.com/noirbizarre/flask-restplus
  license: MIT
  license_file: {{ RECIPE_DIR }}/LICENSE
  summary: 'Fully featured framework for fast, easy and documented API development with Flask'

