{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cliffnotes
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "0.1_3"

source:
  fn: cliffnotes_0.1-3.tar.gz
  url: https://github.com/mndrake/cliffnotes/releases/download/v0.1-3/cliffnotes_0.1-3.tar.gz

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base >=3.3.2
    - r-htmlwidgets >=0.7
    - r-lubridate >=1.5.6
    - r-stringr >=1.0.0
    - r-rmarkdown >=1.1

  run:
    - r-base
    - r-htmlwidgets
    - r-lubridate
    - r-stringr
    - r-rmarkdown

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('cliffnotes')" # [not win]
    - "\"%R%\" -e \"library('cliffnotes')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/mndrake/cliffnotes
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
