{% set name = "credit-model" %}
{% set version = "0.0.2" %}
{% set md5 = "003dc71e3533446d9176a741a0b2d25f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/mndrake/{{ name }}/archive/v{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number: 0

requirements:
  build:
    - python =3.6
    - setuptools

  run:
    - python =3.6
    - scikit-learn=0.18.1
    - pandas
    - flask
    - flask-restplus

test:
  imports:
    - credit_model

about:
  home: https://github.com/mndrake/credit-model
  license: MIT

