{% set name = "aniso8601" %}
{% set version = "3.0.2" %}
{% set md5 = "b539fd9e5a5bfc80b86527c0eca0fa03" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://bitbucket.org/nielsenb/{{ name }}/get/v{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number: 0

requirements:
  build:
    - python =3.6
    - setuptools

  run:
    - python
    - python-dateutil

test:
  imports:
    - aniso8601

about:
  home: https://bitbucket.org/nielsenb/aniso8601
  license: BSD 3-Clause
  summary: A library for parsing ISO 8601 strings.

